const allStates = [
    { "id": "AL", "val": "01", "state": "Alabama", "fact": "Alabama is known as the Heart of Dixie." },
    { "id": "AK", "val": "02", "state": "Alaska", "fact": "Alaska is the largest state in the United States." },
    { "id": "AS", "val": "60", "state": "American Samoa", "fact": "American Samoa is an unincorporated territory of the United States." },
    { "id": "AZ", "val": "04", "state": "Arizona", "fact": "Arizona is home to the Grand Canyon, one of the Seven Wonders of the Natural World." },
    { "id": "AR", "val": "05", "state": "Arkansas", "fact": "Arkansas is known for its natural hot springs." },
    { "id": "CA", "val": "06", "state": "California", "fact": "California is the most populous state in the United States." },
    { "id": "CO", "val": "08", "state": "Colorado", "fact": "Colorado is home to the Rocky Mountains." },
    { "id": "CT", "val": "09", "state": "Connecticut", "fact": "Connecticut is known for its historic coastal towns." },
    { "id": "DE", "val": "10", "state": "Delaware", "fact": "Delaware is the first state to ratify the U.S. Constitution." },
    { "id": "DC", "val": "11", "state": "District of Columbia", "fact": "Washington, D.C. is the capital of the United States." },
    { "id": "FL", "val": "12", "state": "Florida", "fact": "Florida is known as the Sunshine State." },
    { "id": "GA", "val": "13", "state": "Georgia", "fact": "Georgia is the Peach State." },
    { "id": "GU", "val": "66", "state": "Guam", "fact": "Guam is an unincorporated territory of the United States." },
    { "id": "HI", "val": "15", "state": "Hawaii", "fact": "Hawaii is the only U.S. state located in Oceania." },
    { "id": "ID", "val": "16", "state": "Idaho", "fact": "Idaho is known for its potatoes." },
    { "id": "IL", "val": "17", "state": "Illinois", "fact": "Illinois is the home of the world's first skyscraper." },
    { "id": "IN", "val": "18", "state": "Indiana", "fact": "Indiana is known for the Indianapolis 500 race." },
    { "id": "IA", "val": "19", "state": "Iowa", "fact": "Iowa is famous for its cornfields." },
    { "id": "KS", "val": "20", "state": "Kansas", "fact": "Kansas is known as the Sunflower State." },
    { "id": "KY", "val": "21", "state": "Kentucky", "fact": "Kentucky is famous for its horse racing, especially the Kentucky Derby." },
    { "id": "LA", "val": "22", "state": "Louisiana", "fact": "Louisiana is known for its vibrant culture and cuisine." },
    { "id": "ME", "val": "23", "state": "Maine", "fact": "Maine is known for its picturesque coastline." },
    { "id": "MD", "val": "24", "state": "Maryland", "fact": "Maryland is home to the U.S. Naval Academy." },
    { "id": "MA", "val": "25", "state": "Massachusetts", "fact": "Massachusetts is one of the original 13 colonies." },
    { "id": "MI", "val": "26", "state": "Michigan", "fact": "Michigan is known for its Great Lakes and automotive industry." },
    { "id": "MN", "val": "27", "state": "Minnesota", "fact": "Minnesota is the Land of 10,000 Lakes." },
    { "id": "MS", "val": "28", "state": "Mississippi", "fact": "Mississippi is named after the Mississippi River." },
    { "id": "MO", "val": "29", "state": "Missouri", "fact": "Missouri is known as the Show-Me State." },
    { "id": "MT", "val": "30", "state": "Montana", "fact": "Montana is known for its stunning natural landscapes." },
    { "id": "NE", "val": "31", "state": "Nebraska", "fact": "Nebraska is the only triply landlocked U.S. state." },
    { "id": "NV", "val": "32", "state": "Nevada", "fact": "Nevada is home to Las Vegas, the entertainment capital of the world." },
    { "id": "NH", "val": "33", "state": "New Hampshire", "fact": "New Hampshire is known for its scenic mountains and lakes." },
    { "id": "NJ", "val": "34", "state": "New Jersey", "fact": "New Jersey is the most densely populated U.S. state." },
    { "id": "NM", "val": "35", "state": "New Mexico", "fact": "New Mexico is known for its rich Native American and Hispanic cultures." },
    { "id": "NY", "val": "36", "state": "New York", "fact": "New York is home to the Statue of Liberty and Times Square." },
    { "id": "NC", "val": "37", "state": "North Carolina", "fact": "North Carolina is known for its beautiful beaches and mountains." },
    { "id": "ND", "val": "38", "state": "North Dakota", "fact": "North Dakota is known for its vast prairies." },
    { "id": "MP", "val": "69", "state": "Northern Mariana Islands", "fact": "The Northern Mariana Islands are a U.S. commonwealth in the Pacific Ocean." },
    { "id": "OH", "val": "39", "state": "Ohio", "fact": "Ohio is the birthplace of aviation pioneers, the Wright brothers." },
    { "id": "OK", "val": "40", "state": "Oklahoma", "fact": "Oklahoma is known for its diverse landscapes, including prairies and mountains." },
    { "id": "OR", "val": "41", "state": "Oregon", "fact": "Oregon is home to Crater Lake, the deepest lake in the United States." },
    { "id": "PW", "val": "70", "state": "Palau", "fact": "Palau is an independent country in free association with the United States." },
    { "id": "PA", "val": "42", "state": "Pennsylvania", "fact": "Pennsylvania is home to the Liberty Bell and Independence Hall." },
    { "id": "PR", "val": "72", "state": "Puerto Rico", "fact": "Puerto Rico is a U.S. territory in the Caribbean." },
    { "id": "RI", "val": "44", "state": "Rhode Island", "fact": "Rhode Island is the smallest state in the United States." },
    { "id": "SC", "val": "45", "state": "South Carolina", "fact": "South Carolina is known for its historic plantations and gardens." },
    { "id": "SD", "val": "46", "state": "South Dakota", "fact": "South Dakota is home to Mount Rushmore." },
    { "id": "TN", "val": "47", "state": "Tennessee", "fact": "Tennessee is known for its vibrant country music scene." },
    { "id": "TX", "val": "48", "state": "Texas", "fact": "Texas is the second-largest state in both area and population." },
    { "id": "UM", "val": "74", "state": "U.S. Minor Outlying Islands", "fact": "The U.S. Minor Outlying Islands are unincorporated territories." },
    { "id": "UT", "val": "49", "state": "Utah", "fact": "Utah is known for its stunning national parks, including Zion and Bryce Canyon." },
    { "id": "VT", "val": "50", "state": "Vermont", "fact": "Vermont is known for its picturesque landscapes and maple syrup production." },
    { "id": "VI", "val": "78", "state": "Virgin Islands", "fact": "The U.S. Virgin Islands are an unincorporated territory in the Caribbean." },
    { "id": "VA", "val": "51", "state": "Virginia", "fact": "Virginia is known for its historic sites, including Jamestown and Colonial Williamsburg." },
    { "id": "WA", "val": "53", "state": "Washington", "fact": "Washington is home to the Space Needle and Microsoft headquarters." },
    { "id": "WV", "val": "54", "state": "West Virginia", "fact": "West Virginia is known for its mountainous terrain." },
    { "id": "WI", "val": "55", "state": "Wisconsin", "fact": "Wisconsin is famous for its cheese production." },
    { "id": "WY", "val": "56", "state": "Wyoming", "fact": "Wyoming is the least populous state in the United States." }
];

export default allStates;
